/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#0f00da",
        "primary-container": "#2d2dff",
        "on-primary": "#ffffff",
        "on-primary-container": "#c9caff",
        "primary-fixed": "#e1e0ff",
        "primary-fixed-dim": "#bfc1ff",
        "on-primary-fixed": "#03006d",
        "on-primary-fixed-variant": "#1200ed",
        "secondary": "#4f54b2",
        "secondary-container": "#959afd",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#292c8b",
        "secondary-fixed": "#e1e0ff",
        "secondary-fixed-dim": "#bfc1ff",
        "on-secondary-fixed": "#03006d",
        "on-secondary-fixed-variant": "#373b99",
        "tertiary": "#811500",
        "tertiary-container": "#ab1f00",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#ffbfb1",
        "tertiary-fixed": "#ffdad3",
        "tertiary-fixed-dim": "#ffb4a4",
        "on-tertiary-fixed": "#3e0500",
        "on-tertiary-fixed-variant": "#8c1800",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "background": "#f9f9f9",
        "on-background": "#1a1c1c",
        "surface": "#f9f9f9",
        "surface-dim": "#dadada",
        "surface-bright": "#f9f9f9",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f3f3",
        "surface-container": "#eeeeee",
        "surface-container-high": "#e8e8e8",
        "surface-container-highest": "#e2e2e2",
        "surface-variant": "#e2e2e2",
        "surface-tint": "#393bff",
        "on-surface": "#1a1c1c",
        "on-surface-variant": "#454557",
        "outline": "#767589",
        "outline-variant": "#c6c4da",
        "inverse-surface": "#2f3131",
        "inverse-on-surface": "#f1f1f1",
        "inverse-primary": "#bfc1ff",
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px",
      },
      fontFamily: {
        "headline": ["Inter", "sans-serif"],
        "display": ["Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
}
